services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: portfolio
    ports:
      - 5173:5173
    environment:
      - VITE_RESUMEAI_AGENT_URL=http://localhost:8000
      - VITE_MODE=development
      - VITE_CHAT_DISABLED=false
    volumes:
      - .:/app
      - /app/node_modules
    command: ["yarn", "dev", "--host"]
