apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
  labels:
    name: portfolio-app-deployment

spec:
  template:
    metadata:
      name: portfolio-app
      labels:
        name: portfolio-app
    spec:
      containers:
        - image: kishanlalbj/personal-portfolio
          name: portfolio-image
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
  replicas: 2
  selector:
    matchLabels:
      name: portfolio-app
